services:
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: pulsedash_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    networks:
      - pulsedash-network

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: pulsedash_redis
    volumes:
      - redis_data:/data:Z
    networks:
      - pulsedash-network

  minio:
    image: quay.io/minio/minio
    container_name: pulsedash_minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data:Z
    command: server /data --console-address ":9001"
    networks:
      - pulsedash-network

  api:
    build:
      context: .
      dockerfile: Docker/Api.Dockerfile
      target: prod
    container_name: pulsedash_api
    env_file: .env
    ports:
      - "9050:9050"
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - ./src:/app/src:Z
      - ./alembic.ini:/app/alembic.ini:Z
      - ./src/api/db/migrations:/app/src/api/db/migrations:Z
    networks:
      - pulsedash-network

  celery:
    build:
      context: .
      dockerfile: Docker/Celery.Dockerfile
    container_name: pulsedash_celery
    env_file: .env
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - ./src:/app/src:Z
    command: uv run celery -A src.api.core.celery_app worker --loglevel=info --concurrency=4
    networks:
      - pulsedash-network

  tunnel:
    image: docker.io/cloudflare/cloudflared:latest
    container_name: pulsedash_tunnel
    restart: unless-stopped
    env_file: .env
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - api
    networks:
      - pulsedash-network
    environment:
      - CLOUDFLARED_NO_QUIC=true

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  pulsedash-network:
    driver: bridge
